export const ActionTypes = {
  ADD_PROJECT: "ADD_PROJECT",
  ADD_USER: "ADD_USER",
  LIST_PROJECT: "LIST_PROJECT",
  EDIT_PROJECT: "EDIT_PROJECT",
  LIST_USERS: "LIST_USERS",
  SHOW_DIALOG: "SWOW_DIALOG",
  HIDE_DIALOG: "HIDE_DIALOG",
  ERROR: "ERROR",
};
